### ISSUE TITLE
Fatal: Bug: ValueError: Can't find a pure Python 3 wheel for 'marisa-trie>=0.7.7'

### ISSUE THREAD

**Issue by carafelix** [SyedAhkam/spacy-wasm#1]
Console Error:
```py
Uncaught (in promise) PythonError: Traceback (most recent call last):
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 234, in __step
    result = coro.throw(exc)
  File "/lib/python3.10/site-packages/_pyodide/_base.py", line 506, in eval_code_async
    await CodeRunner(
  File "/lib/python3.10/site-packages/_pyodide/_base.py", line 359, in run_async
    await coroutine
  File "<exec>", line 33, in <module>
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 549, in install
    await transaction.gather_requirements(requirements)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 306, in gather_requirements
    await gather(*requirement_promises)
  File "/lib/python3.10/asyncio/futures.py", line 284, in __await__
    yield self  # This tells Task to wait for completion.
  File "/lib/python3.10/asyncio/tasks.py", line 304, in __wakeup
    future.result()
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 234, in __step
    result = coro.throw(exc)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 319, in add_requirement
    await self.add_wheel(wheel, extras=set())
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 436, in add_wheel
    await self.gather_requirements(wheel.requires(extras))
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 306, in gather_requirements
    await gather(*requirement_promises)
  File "/lib/python3.10/asyncio/futures.py", line 284, in __await__
    yield self  # This tells Task to wait for completion.
  File "/lib/python3.10/asyncio/tasks.py", line 304, in __wakeup
    future.result()
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 234, in __step
    result = coro.throw(exc)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 310, in add_requirement
    return await self.add_requirement_inner(req)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 421, in add_requirement_inner
    await self.add_wheel(wheel, req.extras)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 436, in add_wheel
    await self.gather_requirements(wheel.requires(extras))
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 306, in gather_requirements
    await gather(*requirement_promises)
  File "/lib/python3.10/asyncio/futures.py", line 284, in __await__
    yield self  # This tells Task to wait for completion.
  File "/lib/python3.10/asyncio/tasks.py", line 304, in __wakeup
    future.result()
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 234, in __step
    result = coro.throw(exc)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 310, in add_requirement
    return await self.add_requirement_inner(req)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 421, in add_requirement_inner
    await self.add_wheel(wheel, req.extras)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 436, in add_wheel
    await self.gather_requirements(wheel.requires(extras))
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 306, in gather_requirements
    await gather(*requirement_promises)
  File "/lib/python3.10/asyncio/futures.py", line 284, in __await__
    yield self  # This tells Task to wait for completion.
  File "/lib/python3.10/asyncio/tasks.py", line 304, in __wakeup
    future.result()
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 232, in __step
    result = coro.send(None)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 310, in add_requirement
    return await self.add_requirement_inner(req)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 408, in add_requirement_inner
    wheel = find_wheel(metadata, req)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 276, in find_wheel
    raise ValueError(
ValueError: Can't find a pure Python 3 wheel for 'marisa-trie>=0.7.7'.
See: https://pyodide.org/en/stable/usage/faq.html#micropip-can-t-find-a-pure-python-wheel
You can use `micropip.install(..., keep_going=True)`to get a list of all packages with missing wheels.
    PythonError https://cdn.jsdelivr.net/pyodide/v0.21.0/full/pyodide.asm.js:10
    new_error https://cdn.jsdelivr.net/pyodide/v0.21.0/full/pyodide.asm.js:10
    method_call_trampoline https://cdn.jsdelivr.net/pyodide/v0.21.0/full/pyodide.asm.js:10
    callPyObjectKwargs https://cdn.jsdelivr.net/pyodide/v0.21.0/full/pyodide.asm.js:10
    callPyObject https://cdn.jsdelivr.net/pyodide/v0.21.0/full/pyodide.asm.js:10
    wrapper https://cdn.jsdelivr.net/pyodide/v0.21.0/full/pyodide.asm.js:10
pyodide.asm.js:10:147827
```

**Comment by sedbytes** [comment]
Hi, 

Thanks for reporting this issue. 

Marisa certainly isn't a pure-python module thus pyodide devs need to make an explicit case for it. Could you please make a packaging request for `marisa-trie` over on the [pyodide](https://github.com/pyodide/pyodide) repository? 

I noticed a while back that this project is in a broken state and I haven't had the time to look into it yet. Your issue is a good reminder I shouldn't forget about this. I'll look into this specific problem in detail soon.

**Comment by evanbattaglia** [comment]
I assume this was working at some point in time -- anyone know if it is possible to get this working with old packages? I tried changing the version of pyodide referenced in index.html but that didn't work.

**Comment by evanbattaglia** [comment]
I was able to get around the marisa-trie requirement by downloading the langcodes wheel (I didn't see an old version), remove the language-data dependency (that's what uses marisa-trie, and it's actually an optional dependency, but was marked as mandatory for a while). It doesn't seem like pypi.org had an old version, so I modified the METADATA file in the wheel, repackaged the wheel and imported it before the other packaged wheels like spacy. But, then I get another error: `ImportError: cannot import name 'JsArray' from 'pyodide.ffi' (/lib/python3.10/site-packages/pyodide/ffi/__init__.py)`

This is fixed by switching to pyodide 0.22, but I then get `ValueError: Wheel was built with Emscripten v3.1.14 but Pyodide was built with Emscripten v3.1.27`. So, probably the wheels need to rebuilt, or the ffi error avoided another way by using an older version of some package.

**Comment by evanbattaglia** [comment]
I was able to get it working finally by replacing `JsArray` with `JsProxy` in the urllib3 wheel. It seems like emscripten support in urllib3 has always required JsArray, which is only in pyodide >= 0.22, so I don't know how it worked previously.

**Comment by Talha-Farrukh** [comment]
> I was able to get around the marisa-trie requirement by downloading the langcodes wheel (I didn't see an old version), remove the language-data dependency (that's what uses marisa-trie, and it's actually an optional dependency, but was marked as mandatory for a while). It doesn't seem like pypi.org had an old version, so I modified the METADATA file in the wheel, repackaged the wheel and imported it before the other packaged wheels like spacy. But, then I get another error: `ImportError: cannot import name 'JsArray' from 'pyodide.ffi' (/lib/python3.10/site-packages/pyodide/ffi/__init__.py)`
> 
> This is fixed by switching to pyodide 0.22, but I then get `ValueError: Wheel was built with Emscripten v3.1.14 but Pyodide was built with Emscripten v3.1.27`. So, probably the wheels need to rebuilt, or the ffi error avoided another way by using an older version of some package.

Can I have a look at your implementation because I'm trying to impliment this on React project but getting this marisa-trie related error.

**Comment by sedbytes** [comment]
Hi @evanbattaglia,

Hope you're doing well. Thanks for putting in effort to fix these errors. 

I would appreciate if you can take some time out to perhaps craft a patch / PR to get the upstream project working again. I will review it asap & merge.

> To others, I'm sorry for my inactivity.

**Comment by evanbattaglia** [comment]
@SyedAhkam 
I only got it working only by adding manually-modified wheels (unzipped, changed files, rezipped):
- langcodes to remove the dependency on language-data. Just made issue so this can be fixed upstream: https://github.com/georgkrause/langcodes/issues/37
- urllib to remove JsArray dependency. The correct solution to this is to update to pyodide >= 0.22 but that would require recompiling the wheels

I also had another problem trying to run pyodide 0.21 in a chrome extension which I didn't have with pyodide 0.28. So the right thing to do seems to be to update pyodide. But I'm very unfamiliar with the process of recompiling the wheels and I felt that was going to take me multiple days to figure out.

https://github.com/evanbattaglia/spacy-wasm/commit/b1594f9bdf54629faaaa487815ccfcae65aa048d is enough to fix it for now anyway. It feels like a hack but if you want me to make a PR with that I can certainly do so.

**Comment by sedbytes** [comment]
@evanbattaglia 

Thanks.

I am aligned that the right solution is to bump pyodide to v0.28. Leave the wheel re-compilation to me, I'll figure it out again using exodide.

Question: Is the langcodes issue still a blocker after bumping pyodide?

**Comment by evanbattaglia** [comment]
> Is the langcodes issue still a blocker after bumping pyodide?

Good point, yes, it probably will be. From what I can tell, langcodes 3.3.0 through 3.5.0 require language-data, but 3.0.0 through 3.2.0 do not, so locking to that version might work, if possible (I'm really unfamiliar with the ecosystem/tooling). I didn't  see wheels for those versions on pypi.
